### ISSUE TITLE
Issues with custom events

### ISSUE THREAD

**Issue by Index154** [Venterok/HullBreakerCompany#15]
Easy to reproduce:
- "SpawnableEnemies = off" does not work and will cause an error. This would be a good option to have in case you want to only modify outside enemy spawn chances in an event
- SpawnableOutsideEnemies seems to have no effect. I did several tests but the spawn rates of the enemies were seemingly not changed
- Trying to change the color of the InGameMessage by for example adding <color="white"> will cause an error at launch and the event seems to not be available in the game

I've also had errors saying something like "Key has already been added: MouthDogAI" or something like that but I'm not sure what caused it. I had two custom events, one setting eyelessdogs spawn chance to 0 and one setting it to 128. Maybe it was a conflict between them?

I hope this issue report isn't too undetailed. If you would like the exact error messages I can go reproduce them again and copy them. But I think you could probably find them easily yourself too.

Thanks for the cool mod!

**Comment by Venterok** [comment]
Thanks for the report, I know that there are a lot of problems with the custom event, in the next update I will redo them a little, and all the problems should disappear

**Comment by Venterok** [comment]
In v1.3.4 I already forgot that I disabled some of the CustomEvent functions, which is why off didn’t work. In v1.3.5 I fixed all the errors, only yes, events that increase and decrease the spawn rate at the same time cannot work, but I made sure that the last activated one sets the spawn, without errors. And the text color cannot be changed in the config, but I added white as the main color in the code.

My events in v1.3.5

Dog spawn
```cfg
[CustomEvent]

EventID = MouthDog

EventWeight = 1000

InGameMessage = Barking

InGameShortMessage = Barking

SpawnableEnemies = off

SpawnableOutsideEnemies = eyelessdogs

EnemyRarity = 1285
```


DogLess
```cfg
[CustomEvent]

EventID = MouthDogLess

EventWeight = 0

InGameMessage = No barking

InGameShortMessage = No barking

SpawnableEnemies = off

SpawnableOutsideEnemies = eyelessdogs

EnemyRarity = 0

```
