### ISSUE TITLE
more details for difficulty configuration

### ISSUE THREAD

**Issue by marioman99HATENA** [Venterok/HullBreakerCompany#27]
The current config doesn't provide much context for what the values change compared to the vanilla game.

For example, I am trying to tweak the difficulty so it is in between the vanilla level and the level offered in the mod. Right now, there are simply too many enemies spawning right inside the entrance. I am wondering if this is a conflict with a map generation (ie. CoomfyDungeon), but I'm not sure. 

If there was an explanation for values such as "BunkerEnemyScale" as well as a provided vanilla value for "MaxEnemyPowerCount" and "MaxOutsideEnemyPowerCount" that would be very helpful. I also think a community discord would alleviate some of these worries!

Thanks, and good work so far!

**Comment by Index154** [comment]
The way this mod handles the BunkerEnemyScale is rather problematic because in vanilla this value is not static but a curve (called SpawnAmountCurve in other mods), increasing step by step the longer the day goes on.
For most moons it seems to start between 0 and -3 and then climbs up to a maximum of around 15 by the very end of the day. This leads to monsters slowly accumulating the longer you stay. Sometimes you will have a few early spawns but nothing terrible.

However, this mod sets the value to 256 by default which makes all the inside enemies spawn immediately until the max power count is reached, making the game almost impossible. And even if you do set it to a more normal value like -1, it won't increase as the day goes on from what I could tell from the logs.

There's a very useful mod for changing enemy spawn rates and other settings called LethalQuantities. The Thunderstore description explains the mechanics pretty well. I recommend checking it out (although that mod also still has some issues)

**Comment by marioman99HATENA** [comment]
> The way this mod handles the BunkerEnemyScale is rather problematic because in vanilla this value is not static but a curve (called SpawnAmountCurve in other mods), increasing step by step the longer the day goes on. For most moons it seems to start between 0 and -3 and then climbs up to a maximum of around 15 by the very end of the day. This leads to monsters slowly accumulating the longer you stay. Sometimes you will have a few early spawns but nothing terrible.
> 
> However, this mod sets the value to 256 by default which makes all the inside enemies spawn immediately until the max power count is reached, making the game almost impossible. And even if you do set it to a more normal value like -1, it won't increase as the day goes on from what I could tell from the logs.
> 
> There's a very useful mod for changing enemy spawn rates and other settings called LethalQuantities. The Thunderstore description explains the mechanics pretty well. I recommend checking it out (although that mod also still has some issues)

Yeah, the immediate spawns are the problem for my friends and I. Very interesting, thank you for the explanation. I'll check the mod out!
